CREATE TABLE IF NOT EXISTS users (
    id SERIAL PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    first_name VARCHAR(255),
    last_name VARCHAR(255),
    father_name VARCHAR(255),
    father_mobile VARCHAR(20),
    father_email VARCHAR(255),
    mother_name VARCHAR(255),
    mother_mobile VARCHAR(20),
    mother_email VARCHAR(255),
    dob DATE,
    gender VARCHAR(50),
    nationality VARCHAR(100) DEFAULT 'Indian',
    city VARCHAR(100),
    state VARCHAR(100),
    pincode VARCHAR(20),
    highest_qualification VARCHAR(100),
    university VARCHAR(255),
    current_semester VARCHAR(50),
    cgpa NUMERIC(4,2),
    graduation_year INTEGER,
    work_experience JSONB DEFAULT '[]',
    declarations JSONB DEFAULT '{}',
    document_urls JSONB DEFAULT '{}'
);
